### ISSUE TITLE
build_inputs_with_special_tokens

### ISSUE THREAD

**Issue by fengxb2077** [lilongxian/BaiYang-chatGLM2-6B#3]
build_inputs_with_special_tokensa 方法不是返回 [gMASK],<sop> sentence1 sentenc2<eop>吗？
怎么会返回您说的chatGLM2:input_ids 为 “c + t”： a1,a2,...an,[gMASK],<sop> b1,b2,...bn,<eop>呢？

**Comment by lilongxian** [comment]
我对GLM2官方tokenization.py代码里将[gmask][sop]提到a句前面的做法感到十分困惑不解，所以我这里数据建模沿用的还是GLM1的设计思想，这种比较合理。但从GLM2后来7月4日公布的微调训练脚本里看，GLM2并没有使用官方tokenization.py中的build_inputs_with_special_tokens方法，而是使用了和llama一样的拼接方法：

GLM2：
a_ids = tokenizer.encode(text=prompt, add_special_tokens=True, truncation=True,
                                         max_length=data_args.max_source_length)
                b_ids = tokenizer.encode(text=answer, add_special_tokens=False, truncation=True,
                                         max_length=data_args.max_target_length)

                context_length = len(a_ids)
                input_ids = a_ids + b_ids + [tokenizer.eos_token_id]
                labels = [tokenizer.pad_token_id] * context_length + b_ids + [tokenizer.eos_token_id]

LLAMA:
sep = [self.sep_token_id]
        cls = [self.cls_token_id]

        if token_ids_1 is None:
            return len(cls + token_ids_0 + sep) * [0]
        return len(cls + token_ids_0 + sep) * [0] + len(token_ids_1 + sep) * [1]

由于我的这版微调训练模型是6月30日开始反向研究GLM2源码基础上复现出来的，当时GLM2官方微调训练还没有开源，看不到官方怎么设计，所以我才这样设计的。

从GLM2整体的代码设计来看，GLM2相比较LLAMA的创新点只有三处：
1， 量化训练
2，使用MQA SDPA的flash att
3, 支持万级tokens（这块目前我觉得还有调正空间，我近日将修改GLM2万级tokens的支持方式并开源）

其他方面，GLM2和LLAMA无异。

**Comment by fengxb2077** [comment]
好的，非常感谢您的解答！！！
