### ISSUE TITLE
ptuning微调后推理错误且重复

### ISSUE THREAD

**Issue by QJShan** [lilongxian/BaiYang-chatGLM2-6B#4]
博主 你好！
我在chatglm2-6b的issue区看到了你的精彩评论，
请问ptuning微调后出现大量重复的问题你有解决吗。

**Comment by lilongxian** [comment]
你好！非常感谢你的关注！
GLM2回复句重复的问题的确很明显，这个问题可能与模型预训练权重有很大关系，另外也生成回复句的token停止条件又关系，我也正在想办法, ，，，，

**Comment by QJShan** [comment]
> 你好！非常感谢你的关注！ GLM2回复句重复的问题的确很明显，这个问题可能与模型预训练权重有很大关系，另外也生成回复句的token停止条件又关系，我也正在想办法, ，，，，

我使用官方的ptuning在自己的数据集上进行微调，出现loss不收敛的情况。(chatglm2-6B),同样的训练集，GLM1没这个问题。

**Comment by QJShan** [comment]
还有，博主你在微调时候用的torch是哪个版本，GLM2内部处理会针对不同版本走不同的路，我这边使用的是>2的版本。我不确定这个是否会有影响。

**Comment by lilongxian** [comment]
我用的是pytorch 1.13.1, 感觉还好.

如果loss不收敛，你试试把初始学习率改小，另外你看你的显存如果允许的话可以把批改大点，批大小==per_device_train_batch_size * gradient_accumulation_steps
比如：
--per_device_train_batch_size 1  --gradient_accumulation_steps 20

**Comment by lilongxian** [comment]
是的，GLM2源码支持pytorch 2.0版本。可以多测试下看，

**Comment by QJShan** [comment]
> 我用的是pytorch 1.13.1, 感觉还好.
> 
> 如果loss不收敛，你试试把初始学习率改小，另外你看你的显存如果允许的话可以把批改大点，批大小==per_device_train_batch_size * gradient_accumulation_steps 比如： --per_device_train_batch_size 1 --gradient_accumulation_steps 20

好的，谢谢
